### ISSUE TITLE
Credits again

### ISSUE THREAD

**Issue by varlesh** [vinceliuice/Canta-kde#7]
Why i'm again not seen my name on AUTHORS?
I'm not against forks or themes based on my themes. But you must point about original copyright and authors!!!
if next time i'm not seen my name on AUTHORS and description  - i'm open dispute on Pling distributor  about copyright infringement.

https://github.com/vinceliuice/vimix-kde/issues/3

**Comment by vinceliuice** [comment]
Sorry about this! I have been too busy recently, so I have not taken care of this theme and forgot this. I updated the AUTHORS and README file just now
